### PR TITLE
ARROW-5350 extend filter kernel to support list arrays

### PR DESCRIPTION
**Pull request by yordan-pavlov**
I have made some progress with the support of list arrays in the filter kernel. 
filtering of primitive value list arrays appears to be working and the test is passing.

apologies for the amount of changes, I created my branch from the latest in arrow/master which appears to add some more changes

### CODE REVIEW

**Comment by nevi-me** [comment]
no worries, I'll try rebase so that the additional changes are filtered out, then I'll have a look at the changes that you've made. I might only be able to do this next week though

**Comment by yordan-pavlov** [comment]
@nevi-me I have made some more progress - I have ported the filter_non_primitive_item_list_array macro; next I will be looking at potential performance improvements over the next few days

**Comment by yordan-pavlov** [comment]
@nevi-me I have had another look at the list array filter implementation - the way selected lists are copied looks a bit naiive and I suspect it should be much more efficient if the underlying data is copied instead; 
however this will take time to benchmark and do properly and that would unnecessarily delay this MR; 
therefore I propose that this change is merged as is and any performance improvements to array list filtering are done in a separate MR;
let me know what you think.

**Comment by nevi-me** [comment]
> @nevi-me I have had another look at the list array filter implementation - the way selected lists are copied looks a bit naiive and I suspect it should be much more efficient if the underlying data is copied instead;
> however this will take time to benchmark and do properly and that would unnecessarily delay this MR;
> therefore I propose that this change is merged as is and any performance improvements to array list filtering are done in a separate MR;
> let me know what you think.

Happy with your suggestion, and thanks for working on this. I'll merge this then open a PR on the Apache repo

**Pull request merged**
